
services:
  payroll_db:
    build: 
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: mysql_payroll_service
    restart: always
    ports:
      - 1121:3306
    volumes:
      - ./Config/mysql:/var/lib/mysql
    hostname: apps_database
    networks:
      - red_microservicios
    healthcheck:
        test: ["CMD","mysql", "-u", "root", "-pPayRollService123*"]
        interval: 30s
        timeout: 10s
        retries: 5
# --------------------------------------------------------------------
  # - The adminer is a tool for managing content in databases.
  adminer:
    image: adminer
    container_name: adminer_payroll_service
    restart: always
    ports:
      - 1122:8080
    networks:
      - red_microservicios
# --------------------------------------------------------------------
  payroll_service:
    build:
      context: ./payroll-module
      dockerfile: Dockerfile
    container_name: backend-payroll-service
    restart: always
    environment:
      - TZ=America/Bogota
    ports:
      - 1123:8080
    depends_on:
       payroll_db:
         condition: service_healthy
    networks:
      - red_microservicios
networks:
  red_microservicios:
    external: true