package com.app.payroll_service.mapper;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import com.app.payroll_service.dto.RequestVacationDTO;
import com.app.payroll_service.dto.VacationResponseDTO;
import com.app.payroll_service.models.Vacation;

/**
 * Mapper interface for converting Vacation entities to DTOs and vice versa.
 * Uses MapStruct for automatic implementation generation.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface VacationMapper {

    /**
     * Converts a list of Vacation entities to a list of VacationResponseDTOs.
     *
     * @param vacations list of Vacation entities
     * @return list of VacationResponseDTOs
     */
    List<VacationResponseDTO> toResponseDTOList(List<Vacation> vacations);

    /**
     * Converts a single Vacation entity to a VacationResponseDTO.
     *
     * @param vacation the Vacation entity
     * @return the corresponding DTO
     */
    VacationResponseDTO toResponseDTO(Vacation vacation);

    /**
     * Converts a RequestVacationDTO to a Vacation entity.
     * Some fields are ignored and expected to be set manually in the service layer:
     * - vacationId: generated by the database
     * - takenDays: calculated in the service
     * - status: initialized as "PENDIENTE"
     * - createdAt and updatedAt: handled automatically
     *
     * @param dto the request DTO
     * @return the corresponding Vacation entity
     */
    @Mapping(target = "vacationId", ignore = true)
    @Mapping(target = "takenDays", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Vacation toEntity(RequestVacationDTO dto);

}
